// Helper function to parse OTT strings from the new dataset
const parseOtt = (ottString) => {
    if (!ottString || ottString.toLowerCase() === 'none') return [];
    const normalized = ottString.toLowerCase();
    const services = [];
    if (normalized.includes('disney') || normalized.includes('hotstar')) {
        services.push('Disney+ Hotstar');
    }
    if (normalized.includes('netflix')) {
        services.push('Netflix');
    }
    if (normalized.includes('amazon') || normalized.includes('prime')) {
        services.push('Amazon Prime');
    }
    return [...new Set(services)];
};

// This data is converted from your plan_dataset (1).csv file.
const mockPlans = [
  {
    id: 'P01',
    price: 99,
    dataPerDay: 2.0,
    calls: '200',
    sms: 100,
    validity: 365,
    ottBundles: parseOtt('Disney+'),
    speed: '4G',
    operator: 'TariffGenie',
    tags: ['Yearly Plan', 'Budget Saver'],
    roaming: false,
    popularityScore: 95,
    purchaseCount: 11200,
  },
  {
    id: 'P02',
    price: 249,
    dataPerDay: 3.0,
    calls: 'Unlimited',
    sms: 200,
    validity: 56,
    ottBundles: parseOtt('Netflix'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Binge Watcher', 'Power User'],
    roaming: true,
    popularityScore: 98,
    purchaseCount: 18500,
  },
  {
    id: 'P03',
    price: 199,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 200,
    validity: 84,
    ottBundles: parseOtt('Disney+'),
    speed: '4G',
    operator: 'Airtel',
    tags: ['Binge Watcher', 'Budget Saver'],
    roaming: false,
    popularityScore: 96,
    purchaseCount: 14300,
  },
  {
    id: 'P04',
    price: 99,
    dataPerDay: 5.0,
    calls: '200',
    sms: 200,
    validity: 84,
    ottBundles: parseOtt('Disney+'),
    speed: '4G',
    operator: 'TariffGenie',
    tags: ['Power User', 'Gaming Pro', 'Budget Saver'],
    roaming: true,
    popularityScore: 99,
    purchaseCount: 25100,
  },
  {
    id: 'P05',
    price: 199,
    dataPerDay: 1.5,
    calls: 'Unlimited',
    sms: 200,
    validity: 84,
    ottBundles: parseOtt('None'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Budget Saver'],
    roaming: false,
    popularityScore: 92,
    purchaseCount: 9800,
  },
  {
    id: 'P06',
    price: 149,
    dataPerDay: 1.5,
    calls: '200',
    sms: 100,
    validity: 365,
    ottBundles: parseOtt('Netflix'),
    speed: '5G',
    operator: 'Airtel',
    tags: ['Yearly Plan', 'Binge Watcher', 'Budget Saver'],
    roaming: true,
    popularityScore: 97,
    purchaseCount: 16400,
  },
  {
    id: 'P07',
    price: 299,
    dataPerDay: 1.0,
    calls: '300',
    sms: 100,
    validity: 180,
    ottBundles: parseOtt('Hotstar'),
    speed: '4G',
    operator: 'BSNL',
    tags: ['Yearly Plan'],
    roaming: false,
    popularityScore: 91,
    purchaseCount: 7600,
  },
  {
    id: 'P08',
    price: 799,
    dataPerDay: 5.0,
    calls: '100',
    sms: 50,
    validity: 84,
    ottBundles: parseOtt('None'),
    speed: '4G',
    operator: 'Jio',
    tags: ['Power User', 'Gaming Pro'],
    roaming: false,
    popularityScore: 94,
    purchaseCount: 8100,
  },
  {
    id: 'P09',
    price: 149,
    dataPerDay: 2.0,
    calls: '200',
    sms: 'Unlimited',
    validity: 365,
    ottBundles: parseOtt('Disney+'),
    speed: '4G',
    operator: 'TariffGenie',
    tags: ['Yearly Plan', 'Binge Watcher', 'Budget Saver'],
    roaming: true,
    popularityScore: 98,
    purchaseCount: 19800,
  },
  {
    id: 'P10',
    price: 599,
    dataPerDay: 3.0,
    calls: 'Unlimited',
    sms: 50,
    validity: 28,
    ottBundles: parseOtt('None'),
    speed: '4G',
    operator: 'Airtel',
    tags: ['Power User'],
    roaming: false,
    popularityScore: 88,
    purchaseCount: 6500,
  },
  {
    id: 'P11',
    price: 499,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 28,
    ottBundles: parseOtt('Hotstar'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Binge Watcher'],
    roaming: true,
    popularityScore: 93,
    purchaseCount: 11500,
  },
  {
    id: 'P12',
    price: 249,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 'Unlimited',
    validity: 56,
    ottBundles: parseOtt('Amazon Prime'),
    speed: '5G',
    operator: 'Airtel',
    tags: ['Binge Watcher'],
    roaming: false,
    popularityScore: 95,
    purchaseCount: 13200,
  },
  {
    id: 'P13',
    price: 499,
    dataPerDay: 5.0,
    calls: '200',
    sms: 'Unlimited',
    validity: 365,
    ottBundles: parseOtt('Amazon Prime'),
    speed: '5G',
    operator: 'TariffGenie',
    tags: ['Yearly Plan', 'Power User', 'Binge Watcher', 'Gaming Pro'],
    roaming: true,
    popularityScore: 100,
    purchaseCount: 21000,
  },
  {
    id: 'P14',
    price: 349,
    dataPerDay: 2.5,
    calls: 'Unlimited',
    sms: 100,
    validity: 56,
    ottBundles: parseOtt('None'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Power User'],
    roaming: true,
    popularityScore: 90,
    purchaseCount: 10500,
  },
  {
    id: 'P15',
    price: 459,
    dataPerDay: 1.5,
    calls: 'Unlimited',
    sms: 100,
    validity: 84,
    ottBundles: parseOtt('Amazon Prime'),
    speed: '4G',
    operator: 'Airtel',
    tags: ['Budget Saver', 'Binge Watcher'],
    roaming: false,
    popularityScore: 89,
    purchaseCount: 9200,
  },
  {
    id: 'P16',
    price: 199,
    dataPerDay: 1.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 28,
    ottBundles: parseOtt('None'),
    speed: '4G',
    operator: 'BSNL',
    tags: ['Budget Saver'],
    roaming: false,
    popularityScore: 78,
    purchaseCount: 15000,
  },
  {
    id: 'P17',
    price: 666,
    dataPerDay: 1.5,
    calls: 'Unlimited',
    sms: 100,
    validity: 84,
    ottBundles: parseOtt('Hotstar, Amazon Prime'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Binge Watcher'],
    roaming: true,
    popularityScore: 94,
    purchaseCount: 17800,
  },
  {
    id: 'P18',
    price: 839,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 84,
    ottBundles: parseOtt('Disney+, Netflix'),
    speed: '5G',
    operator: 'Airtel',
    tags: ['Binge Watcher', 'Power User'],
    roaming: true,
    popularityScore: 96,
    purchaseCount: 16200,
  },
  {
    id: 'P19',
    price: 2999,
    dataPerDay: 2.5,
    calls: 'Unlimited',
    sms: 100,
    validity: 365,
    ottBundles: parseOtt('Amazon Prime'),
    speed: '5G',
    operator: 'TariffGenie',
    tags: ['Yearly Plan', 'Power User'],
    roaming: true,
    popularityScore: 97,
    purchaseCount: 14500,
  },
  {
    id: 'P20',
    price: 1799,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 365,
    ottBundles: parseOtt('None'),
    speed: '4G',
    operator: 'BSNL',
    tags: ['Yearly Plan', 'Budget Saver'],
    roaming: false,
    popularityScore: 85,
    purchaseCount: 8800,
  },
  {
    id: 'P21',
    price: 395,
    dataPerDay: 2.0,
    calls: '3000',
    sms: 100,
    validity: 70,
    ottBundles: parseOtt('None'),
    speed: '4G',
    operator: 'BSNL',
    tags: [],
    roaming: false,
    popularityScore: 75,
    purchaseCount: 6500,
  },
  {
    id: 'P22',
    price: 1198,
    dataPerDay: 3.0,
    calls: '300',
    sms: 30,
    validity: 365,
    ottBundles: parseOtt('Disney+'),
    speed: '4G',
    operator: 'TariffGenie',
    tags: ['Yearly Plan', 'Binge Watcher'],
    roaming: true,
    popularityScore: 93,
    purchaseCount: 12800,
  },
  {
    id: 'P23',
    price: 1499,
    dataPerDay: 2.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 84,
    ottBundles: parseOtt('Netflix'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Binge Watcher', 'Power User'],
    roaming: true,
    popularityScore: 92,
    purchaseCount: 11300,
  },
  {
    id: 'P24',
    price: 3359,
    dataPerDay: 2.5,
    calls: 'Unlimited',
    sms: 100,
    validity: 365,
    ottBundles: parseOtt('Disney+, Amazon Prime'),
    speed: '5G',
    operator: 'Airtel',
    tags: ['Yearly Plan', 'Binge Watcher', 'Power User'],
    roaming: true,
    popularityScore: 98,
    purchaseCount: 22000,
  },
  {
    id: 'P25',
    price: 499,
    dataPerDay: 3.0,
    calls: 'Unlimited',
    sms: 100,
    validity: 28,
    ottBundles: parseOtt('Disney+'),
    speed: '5G',
    operator: 'Jio',
    tags: ['Binge Watcher', 'Power User', 'Gaming Pro'],
    roaming: true,
    popularityScore: 91,
    purchaseCount: 19500,
  },
];

module.exports = { mockPlans };

